require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KassociationsController do

  # This should return the minimal set of attributes required to create a valid
  # Kassociation. As you add validations to Kassociation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all kassociations as @kassociations" do
      kassociation = Kassociation.create! valid_attributes
      get :index
      assigns(:kassociations).should eq([kassociation])
    end
  end

  describe "GET show" do
    it "assigns the requested kassociation as @kassociation" do
      kassociation = Kassociation.create! valid_attributes
      get :show, :id => kassociation.id
      assigns(:kassociation).should eq(kassociation)
    end
  end

  describe "GET new" do
    it "assigns a new kassociation as @kassociation" do
      get :new
      assigns(:kassociation).should be_a_new(Kassociation)
    end
  end

  describe "GET edit" do
    it "assigns the requested kassociation as @kassociation" do
      kassociation = Kassociation.create! valid_attributes
      get :edit, :id => kassociation.id
      assigns(:kassociation).should eq(kassociation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Kassociation" do
        expect {
          post :create, :kassociation => valid_attributes
        }.to change(Kassociation, :count).by(1)
      end

      it "assigns a newly created kassociation as @kassociation" do
        post :create, :kassociation => valid_attributes
        assigns(:kassociation).should be_a(Kassociation)
        assigns(:kassociation).should be_persisted
      end

      it "redirects to the created kassociation" do
        post :create, :kassociation => valid_attributes
        response.should redirect_to(Kassociation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved kassociation as @kassociation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Kassociation.any_instance.stub(:save).and_return(false)
        post :create, :kassociation => {}
        assigns(:kassociation).should be_a_new(Kassociation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Kassociation.any_instance.stub(:save).and_return(false)
        post :create, :kassociation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested kassociation" do
        kassociation = Kassociation.create! valid_attributes
        # Assuming there are no other kassociations in the database, this
        # specifies that the Kassociation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Kassociation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => kassociation.id, :kassociation => {'these' => 'params'}
      end

      it "assigns the requested kassociation as @kassociation" do
        kassociation = Kassociation.create! valid_attributes
        put :update, :id => kassociation.id, :kassociation => valid_attributes
        assigns(:kassociation).should eq(kassociation)
      end

      it "redirects to the kassociation" do
        kassociation = Kassociation.create! valid_attributes
        put :update, :id => kassociation.id, :kassociation => valid_attributes
        response.should redirect_to(kassociation)
      end
    end

    describe "with invalid params" do
      it "assigns the kassociation as @kassociation" do
        kassociation = Kassociation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Kassociation.any_instance.stub(:save).and_return(false)
        put :update, :id => kassociation.id, :kassociation => {}
        assigns(:kassociation).should eq(kassociation)
      end

      it "re-renders the 'edit' template" do
        kassociation = Kassociation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Kassociation.any_instance.stub(:save).and_return(false)
        put :update, :id => kassociation.id, :kassociation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested kassociation" do
      kassociation = Kassociation.create! valid_attributes
      expect {
        delete :destroy, :id => kassociation.id
      }.to change(Kassociation, :count).by(-1)
    end

    it "redirects to the kassociations list" do
      kassociation = Kassociation.create! valid_attributes
      delete :destroy, :id => kassociation.id
      response.should redirect_to(kassociations_url)
    end
  end

end
